architecture:
  name: pet

  model:
    cutoff: 5.0

  training:
    num_epochs: 10
    batch_size: 4
    log_interval: 1

# this needs specifying based on the specific dataset
training_set:
  systems: 
    read_from: ../data/ethanol_reduced_100.xyz # file where the positions are stored
    length_unit: Angstrom
  targets:
    energy:
      key: energy # name of the target value
      unit: eV # unit of the target value

test_set: 0.1 # 10 % of the training_set are randomly split and taken for test set
validation_set: 0.1 # 10 % of the training_set are randomly split and for validation set